Azure-Samples/Synapse

Manage/DeployWorkspace/azuredeploy.json
Manage/DeployWorkspace/readme.md
Manage/DeployWorkspace/storage/azuredeploy.json
Manage/DeployWorkspace/storage/azuredeploy.parameters.json
Manage/DeployWorkspace/storage/metadata.json
Manage/DeployWorkspace/storage/readme.md
Manage/DeployWorkspace/workspace/azuredeploy.json
Manage/DeployWorkspace/workspace/azuredeploy.parameters.json
Manage/DeployWorkspace/workspace/metadata.json
Manage/DeployWorkspace/workspace/readme.md

I have added 3 deployment templates:
1. Create workspace and new DataLake storage
2. Create Workspace on existing storage
3. create storage that can be used for Synapse Workspace.

Added Deployment templates that create Synapse workspace

---

Notebooks/PySpark/07 Data Exploration and ML Modeling - NYC taxi predict using Spark MLlib.ipynb

Fix typos in SparkML sample notebook.

Fix typos in SparkML sample notebook

---

Notebooks/Scala/01 Read and write data from Azure Data Lake Storage Gen2.ipynb
Notebooks/Scala/02 Read and write data from Azure Blob Storage WASB.ipynb
Notebooks/Scala/03 Read and write from SQL pool table.ipynb
Notebooks/Scala/04 Using Delta Lake in Azure Synapse.ipynb
Notebooks/placeholder.txt

Add following samples to scala:
01. r/w data from adlsgen2
02. r/w data from blob wasbs
03. r/w data from SQL pool table
04. using delta lake

add more scala samples

---

Notebooks/PySpark/Hitchikers Guide to Delta Lake - Python.ipynb
Notebooks/Scala/Hitchikers Guide to Delta Lake - Scala.ipynb
Notebooks/Spark.NET C#/Hitchikers Guide to Delta Lake - CSharp.ipynb

Fix the cell numbers in instructions for streaming example.

Fix cell numbers in "Hitchhiker's Guide to Delta Lake" notebook

---

Notebooks/Spark.NET C#/GitHub Projects.ipynb

Adding GitHub notebook that I've shown in conference sessions.

Add GitHub notebook

---

README.md

We should add more scenario-focused information instead of just the current technology information.

Added scenario-focused section to readme

---

Notebooks/PySpark/03 Read and write from SQL pool table.ipynb
Notebooks/Scala/03 Read and write from SQL pool table.ipynb

removed TEMP_FOLDER options and used standard read and write.  TEMP_FOLDER option generates error.

Update Spark to DW Connector

---

Notebooks/PySpark/Synapse Link for Cosmos DB samples/Retail/spark-notebooks/pyspark/req.txt

New requirements.

---

SQL/Extension/Readme.md
SQL/Extension/deploy.bat
SQL/Extension/functions/Readme.md
SQL/Extension/functions/microsoft.acosh.sql
SQL/Extension/functions/microsoft.asinh.sql
SQL/Extension/functions/microsoft.dayoccurrence_of_month.sql
SQL/Extension/functions/microsoft.initcap.sql
SQL/Extension/functions/microsoft.instr.sql
SQL/Extension/functions/microsoft.kurtosis.sql
SQL/Extension/functions/microsoft.lpad.sql
SQL/Extension/functions/microsoft.months_between.sql
SQL/Extension/functions/microsoft.next_day.sql
SQL/Extension/schemas/Readme.md
SQL/Extension/schemas/microsoft.sql
SQL/Extension/views/Readme.md
SQL/Extension/views/microsoft.dw_active_queries.sql
SQL/Extension/views/microsoft.dw_active_queue.sql
SQL/Extension/views/microsoft.dw_configuration.sql
SQL/Extension/views/microsoft.dw_extension_version.sql
SQL/Extension/views/microsoft.dw_statistics_information.sql
SQL/Extension/views/microsoft.dw_table_information.sql
SQL/Readme.md

The initial version of the Azure Synapse SQL Extension toolkit includes a set of functions and views that extend the capabilities of Azure Synapse SQL.

Adding the initial version of the Azure Synapse SQL Extension toolkit

---

Notebooks/PySpark/Synapse Link for Cosmos DB samples/Retail/spark-notebooks/pyspark/2SalesForecastingWithAML.ipynb

Fixing DB name

---

Notebooks/PySpark/08 Creating an unmanaged Spark Table.ipynb
Notebooks/Scala/08 Creating an unmanaged Spark Table.ipynb
Notebooks/Scala/09 Creating a managed Spark Table.ipynb
Notebooks/Scala/Updates and GDPR using Delta Lake - Scala.ipynb
Notebooks/Spark.NET C#/08 Creating an unmanaged Spark Table.ipynb
Notebooks/Spark.NET C#/09 Creating a managed Spark Table.ipynb
Notebooks/SparkSQL/08 Creating an unmanaged Spark Table.ipynb
Notebooks/SparkSQL/09 Creating a managed Spark Table.ipynb

1. update following files to make sure display() results show up in the sample center
-  Notebooks/PySpark/08 Creating an unmanaged Spark Table.ipynb
-  Notebooks/Scala/08 Creating an unmanaged Spark Table.ipynb
- Notebooks/Scala/09 Creating a managed Spark Table.ipynb
- Notebooks/SparkSQL/08 Creating an unmanaged Spark Table.ipynb
- Notebooks/SparkSQL/09 Creating a managed Spark Table.ipynb
2. Add display() for spark.net
- Notebooks/Spark.NET C#/08 Creating an unmanaged Spark Table.ipynb
- Notebooks/Spark.NET C#/09 Creating a managed Spark Table.ipynb
3. fix the run failure in following example according to bug https://msdata.visualstudio.com/A365/_queries/edit/882807/?triage=true
- Notebooks/Scala/Updates and GDPR using Delta Lake - Scala.ipynb

fix the display issue and run error in sample notebook

---

Notebooks/PySpark/Hitchikers Guide to Delta Lake - Python.ipynb
Notebooks/Scala/Hitchikers Guide to Delta Lake - Scala.ipynb
Notebooks/Spark.NET C#/Hitchikers Guide to Delta Lake - CSharp.ipynb

Added a compaction example to "Hitchhiker's Guide to Delta Lake" notebooks in Scala, C#, and Python.

Expand "Hitchhiker's Guide to Delta Lake" notebook with compaction example

---

Notebooks/PySpark/Hitchhikers Guide to Hyperspace - Python.ipynb
Notebooks/Scala/Hitchhikers Guide to Hyperspace - Scala.ipynb
Notebooks/Spark.NET C#/Hitchhikers Guide to Hyperspace - CSharp.ipynb

Updating the Hitchhikers Guide to Hyperspace for Apache Spark notebooks to the latest version for Scala, Python and CSharp.

Update latest Hyperspace notebooks

---

SQL/Extension/Readme.md
SQL/Extension/clean.bat
SQL/Extension/clean.sql
SQL/Extension/deploy.bat
SQL/Extension/functions/Readme.md
SQL/Extension/functions/microsoft.firstdayofmonth.sql
SQL/Extension/functions/microsoft.firstdayofquarter.sql
SQL/Extension/functions/microsoft.firstdayofyear.sql

Bug Fixes
1. Added the missing *dbc* schema deployment script
New Features
1. Added the *clean.bat* and associated *clean.sql* file to remove the toolkit
2. Added the *microsoft.firstdayofmonth* function
3. Added the *microsoft.firstdayofquarter* function
4. Added the *microsoft.firstdayofyear* function

Adding the FirstDayOf* functions to the toolkit

---

SQL/Extension/Readme.md
SQL/Extension/clean.sql
SQL/Extension/deploy.bat
SQL/Extension/functions/Readme.md
SQL/Extension/functions/microsoft.date_trunc.sql

Adding the microsoft.date_trunc function to emulate the DATE_TRUNC(date_part, expression) function in IBM Netezza

Adding the DATE_TRUNC function

---

SQL/Extension/functions/microsoft.date_trunc.sql

Bug fix for date_trunc(week, expression) to move the timestamp to 00:00:00

Bug fix for date_trunc(week, expression)

---

Manage/DeployWorkspace/azuredeploy.json
Manage/DeployWorkspace/readme.md
Manage/DeployWorkspace/workspace/azuredeploy.json
Manage/DeployWorkspace/workspace/azuredeploy.parameters.json

Reverts Azure-Samples/Synapse#80

Revert "add customer-managed key (CMK) to deploy templates"

---

Notebooks/PySpark/02 Read and write data from Azure Blob Storage WASB.ipynb
Notebooks/Scala/02 Read and write data from Azure Blob Storage WASB.ipynb

Update sample code:
1. replace sas secret with mssparkutils
2. add plotly samples in the charting file

update sample code with mssparkutils

---

MachineLearning/Tutorial - Bankruptcy Prediction with LightGBM Classifier.ipynb
MachineLearning/Tutorial - Boston house price prediction with VM vs LightGBM vs Spark MLlib.ipynb
MachineLearning/Tutorial - Cognitive Service.ipynb
MachineLearning/Tutorial - Quantile Regression for Drug Discovery with LightGBM Regressor.ipynb
MachineLearning/Tutorial - Twitter Sentiment with Vowpal Wabbit.ipynb

Add following MMLSpark tutorials:
- Tutorial - Bankruptcy Prediction with LightGBM Classifier
- Tutorial - Boston house price prediction with VM vs LightGBM vs Spark MLlib
- Tutorial - Cognitive Service
- Tutorial - Quantile Regression for Drug Discovery with LightGBM Regressor
- Tutorial - Twitter Sentiment with Vowpal Wabbit

add tutorial to knowledge center

---

SQL/Extension/Readme.md
SQL/Extension/clean.sql
SQL/Extension/deploy.bat
SQL/Extension/scripts/microsoft.calendar.sql

- Added the microsoft.calendar data for faster loading via bcp
- Added a non-clustered index and covering statistics to the microsoft.calendar table
- Added automated deployment and cleanup steps for all objects.

Updating the Azure Synapse SQL toolkit deployment scripts

---

Pipelines/ImportADFtoSynapse/README.md
README.md

Add entry "ADF to Synapse Migration Tool" in parent content directory.

Add entry in parent content directory, and minor format fix

---

Diagnostic/SparkDiagnosticEmitter/README.md
Diagnostic/SparkDiagnosticEmitter/diagnostic-emitter-azure-event-hub-conf.txt
Diagnostic/SparkDiagnosticEmitter/diagnostic-emitter-azure-log-analytics-conf.txt
Diagnostic/SparkDiagnosticEmitter/diagnostic-emitter-azure-storage-conf.txt
Diagnostic/SparkDiagnosticEmitter/diagnostic-emitter-multi-destination-conf.txt

Adding following configuration examples:
- diagnostic-emitter-azure-event-hub-conf.txt
- diagnostic-emitter-azure-log-analytics-conf.txt
- diagnostic-emitter-azure-storage-conf.txt
- diagnostic-emitter-multi-destination-conf.txt

Add Spark diagnostic emitter spark pool configuration samples

---

Notebooks/metadata.json

Test 01:  for notebook sample test pipeline

Add metadata file for testing

---

Notebooks/PySpark/05 Using Azure Open Datasets in Synapse.ipynb
Notebooks/PySpark/07 Data Exploration and ML Modeling - NYC taxi predict using Spark MLlib.ipynb
Notebooks/metadata.json

Test 03: notebook sample pipeline

---

SparkCatalogMigration/DatabricksToSynapseMigration/README.md
SparkCatalogMigration/DatabricksToSynapseMigration/scripts/export_metadata_from_databricks_notebook_script.scala
SparkCatalogMigration/DatabricksToSynapseMigration/scripts/import_metadata_to_synapse_notebook_script.ipynb

1. Skip exporting tables from ADB if table contains un-recognized data type 
2. Validate table path when import table

Add validate when export/import tables

---

Manage/DeployWorkspace/workspace/azuredeploy.json

Reverts Azure-Samples/Synapse#134

Revert "Roledefinition for datalake storage account property removal and syna…"

---

MachineLearning/SparkPREDICT_E2E_MLFLOW_SparkML.py
MachineLearning/SparkPREDICT_E2E_MLFLOW_Xgboost.py
MachineLearning/SparkPREDICT_MLFLOW_LightGbm_ADLS.py
MachineLearning/SparkPREDICT_MLFLOW_ONNX_ADLS.py
MachineLearning/SparkPREDICT_MLFLOW_ONNX_AML.py
MachineLearning/SparkPREDICT_MLFLOW_PyTorch_ADLS.py
MachineLearning/SparkPREDICT_MLFLOW_PyTorch_AML.py
MachineLearning/SparkPREDICT_MLFLOW_Sklearn_ADLS.py
MachineLearning/SparkPREDICT_MLFLOW_Sklearn_AML.py
MachineLearning/SparkPREDICT_MLFLOW_SparkML_ADLS.py
MachineLearning/SparkPREDICT_MLFLOW_TensorFlow_ADLS.py
MachineLearning/SparkPREDICT_MLFLOW_TensorFlow_AML.py
MachineLearning/SparkPREDICT_MLFLOW_XgBoost_ADLS.py

End to end example for model creation to registry to scoring

SparkPREDICT Scripts for MLFLOW packed models

---

MachineLearning/SparkPREDICT_E2E_MLFLOW_Sklearn_AML.py

Adding end to end PREDICT example for SKLEARN

---

Notebooks/Scala/Hyperspace for Delta Lake.ipynb

Copy from https://github.com/microsoft/hyperspace/pull/447

Update Hyperspace for Delta Lake notebook

---

Spark/test-file.txt

Test whether the pipeline could only be triggered by changes in specific folder

Test 02: notebook sample pipline

---

PowerShell/GetSynapseRBACInfo.ps1
PowerShell/GetSynapseRBACUser.ps1

Synapse RBAC PowerShell outputs does not provide the names and also its difficult to find a specific user inside RBAC. 
There are 2 scripts in this PR that provides all the RBAC information or, specific information.

synapse-rbac-scripts
